// generated by vite-plugin-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Console: typeof import('./src/components/playground/Console.vue')['default']
    Editor: typeof import('./src/components/playground/Editor.vue')['default']
    Message: typeof import('./src/components/playground/Message.vue')['default']
    Playground: typeof import('./src/components/playground/Playground.vue')['default']
    Preview: typeof import('./src/components/playground/Preview.vue')['default']
    Tab: typeof import('./src/components/playground/Tab.vue')['default']
    TabBar: typeof import('./src/components/playground/TabBar.vue')['default']
    EditorSettings: typeof import('./src/components/settings/EditorSettings.vue')['default']
    InstallSettings: typeof import('./src/components/settings/InstallSettings.vue')['default']
    ManuallyInstallPackage: typeof import('./src/components/settings/ManuallyInstallPackage.vue')['default']
    PackageItem: typeof import('./src/components/settings/PackageItem.vue')['default']
    PackageVersion: typeof import('./src/components/settings/PackageVersion.vue')['default']
    PackagesSettings: typeof import('./src/components/settings/PackagesSettings.vue')['default']
    Settings: typeof import('./src/components/settings/Settings.vue')['default']
    SettingsTab: typeof import('./src/components/settings/SettingsTab.vue')['default']
    WindiCSSSettings: typeof import('./src/components/settings/WindiCSSSettings.vue')['default']
    Button: typeof import('./src/components/ui/Button.vue')['default']
    Container: typeof import('./src/components/ui/Container.vue')['default']
    Navigation: typeof import('./src/components/ui/Navigation.vue')['default']
    Select: typeof import('./src/components/ui/Select.vue')['default']
    SelectItem: typeof import('./src/components/ui/SelectItem.vue')['default']
    Textfield: typeof import('./src/components/ui/Textfield.vue')['default']
  }
}

export { }
